name: pinyin
description: Chinese character conversion pinyin library. Accurate and complete Chinese character dictionary. Fast conversion.
version: 3.1.0
homepage: https://github.com/sun-jiao/dart-pinyin

environment:
  sdk: ">=2.12.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  dio: ^5.4.0
  html: ^0.15.4
  lints: ^2.1.0
  test: ^1.24.0