name: pinyin
description: Chinese character conversion pinyin library. Accurate and complete Chinese character dictionary. Fast conversion.
version: 2.0.3
homepage: https://github.com/sun-jiao/pinyin

environment:
  sdk: ">=2.12.0-259.9.beta <4.0.0"