name: pinyin
description: Chinese character conversion pinyin library. Accurate and complete Chinese character dictionary. Fast conversion.
version: 3.0.1
homepage: https://github.com/sun-jiao/dart-pinyin

environment:
  sdk: ">=2.12.0 <4.0.0"