name: pinyin
description: Chinese character conversion pinyin library. Accurate and complete Chinese character dictionary. Fast conversion.
version: 3.0.1
homepage: https://github.com/sun-jiao/dart-pinyin

environment:
  sdk: ">=2.12.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  dio: ^4.0.6  # do not upgrade it.
  dio_proxy_adapter: ^1.0.1
  lints: ^2.1.0
  test: ^1.24.0